### ISSUE TITLE
undefined variables

### ISSUE THREAD

**Issue by martbhell** [CSC-IT-Center-for-Science/ansible-role-provision-vm#15]
All variables that are used in this role are undocumented and not defined in defaults/

Added them to defaults/main.yml (still undefined):

https://github.com/CSC-IT-Center-for-Science/ansible-role-provision-vm/tree/default_variables

**Comment by rlaurika** [comment]
Thanks for reporting!

This has been addressed by these pull requests:
https://github.com/CSC-IT-Center-for-Science/ansible-role-provision-vm/pull/20
https://github.com/CSC-IT-Center-for-Science/ansible-role-provision-vm/pull/22
